indata <- read.delim(file.choose(),header=1, sep = ";")
indata$Date <- as.Date(indata$Date,"%d/%m/%Y")
subdata <- subset(indata,indata$Date==as.Date("02/01/2007","%m/%d/%Y") | indata$Date==as.Date("02/02/2007","%m/%d/%Y"))
subdata$datetime <- as.POSIXct(paste(subdata$Date,subdata$Time),format = "%Y-%m-%d %H:%M:%S")
subdata$Global_active_power <- as.numeric(levels(subdata$Global_active_power)[subdata$Global_active_power])
subdata$Global_reactive_power <- as.numeric(levels(subdata$Global_reactive_power)[subdata$Global_reactive_power])
subdata$Voltage <- as.numeric(levels(subdata$Voltage)[subdata$Voltage])
subdata$Global_intensity <- as.numeric(levels(subdata$Global_intensity)[subdata$Global_intensity])
subdata$Sub_metering_1 <- as.numeric(levels(subdata$Sub_metering_1)[subdata$Sub_metering_1])
subdata$Sub_metering_2 <- as.numeric(levels(subdata$Sub_metering_2)[subdata$Sub_metering_2])
png(filename = "plot4.png",width = 480, height = 480, units = "px" )
par(mfrow = c(2,2))
plot(subdata$datetime,subdata$Global_active_power, type = "l",ylab = "Global Active Power", xlab = "")
plot(subdata$datetime,subdata$Voltage, type = "l",ylab = "Voltage", xlab = "datetime")
plot(subdata$date,subdata$Sub_metering_1, type ="l", ylab = "Energy Sub Metering",xlab = "" )
points(subdata$date,subdata$Sub_metering_2, type ="l",col = "red")
points(subdata$date,subdata$Sub_metering_3, type ="l",col = "blue")
legend("topright",legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"), col = c(1,2,4),  bty = "n", lty = 1, cex = .75)
plot(subdata$datetime,subdata$Global_reactive_power, type = "l",ylab = "Global_reactive_power", xlab = "datetime")
dev.off()